/* Generated by tools/build-sw.cjs. Install atomically; upgrade on user action. */
const VERSION = 'v3-ce9a870851ce';
const ASSETS = [
  "./",
  "assets/core.js",
  "assets/favicon-v3.ico",
  "assets/field.js",
  "assets/home.js",
  "assets/icon-1024-v3.png",
  "assets/icon-16-v3.png",
  "assets/icon-180-v3.png",
  "assets/icon-180.png",
  "assets/icon-192-v3.png",
  "assets/icon-192.png",
  "assets/icon-32-v3.png",
  "assets/icon-48-v3.png",
  "assets/icon-512-v3.png",
  "assets/icon-512.png",
  "assets/icon-maskable-512-v3.png",
  "assets/icon-maskable-512.png",
  "assets/icon-v3.svg",
  "assets/icon.svg",
  "assets/lesson.js",
  "assets/model.js",
  "assets/practice.js",
  "assets/style.css",
  "data/lessons.json",
  "data/phrases.json",
  "field.html",
  "index.html",
  "lessons/0001-arrival-greeting-car-exit.html",
  "lessons/0002-small-talk-dress-honeymoon.html",
  "lessons/0003-breaking-the-ice-reassurance.html",
  "lessons/0004-getting-to-know-the-couple.html",
  "lessons/0005-week-1-review-roleplay.html",
  "lessons/0006-basic-pose-direction.html",
  "lessons/0007-directing-movement-sequences.html",
  "lessons/0008-directing-expressions-eye-contact.html",
  "lessons/0009-micro-adjustment-direction.html",
  "lessons/0010-week-2-review-roleplay.html",
  "lessons/0011-specific-compliments.html",
  "lessons/0012-handling-unexpected-situations.html",
  "lessons/0013-redirecting-heavy-conversations.html",
  "lessons/0014-recovery-strategies.html",
  "lessons/0015-week-3-review-roleplay.html",
  "lessons/0016-wrap-up-thank-you.html",
  "lessons/0017-following-up-on-deliverables.html",
  "lessons/0018-cross-cultural-client-communication.html",
  "lessons/0019-comprehensive-freetalk.html",
  "lessons/0020-4-week-comprehensive-roleplay-self-asses.html",
  "manifest.webmanifest",
  "practice.html"
];
const HASHES = {
  "assets/core.js": "666bcf6feda10aa28b696979bd03f81a0fd686edcb671e5d727ee1ca020f9052",
  "assets/favicon-v3.ico": "584b8eddfdb245bcb167c616ac54fddc95ebf6cdeeb501d28e984050dd36c8bb",
  "assets/field.js": "75a71826df3c2a6077a131141a982712d09c04454394acb8a713055c27e58efe",
  "assets/home.js": "cdb2ef53f070a0f7c08f6ea35f85d4f286f6a29a0162a5ba14125c7a47ad82e6",
  "assets/icon-1024-v3.png": "d0f2bb04eba45b5c86e1b36b7baa6206a7677245b9115eeb5cd060cc855f6f82",
  "assets/icon-16-v3.png": "f1e6c17d9c0c77d28053598b76e0aae169853184eb028d05935e8fdb8aee0637",
  "assets/icon-180-v3.png": "cce27428858763d96b36898ac314ebe5da35c56c329cc0ab116228da3242cf1d",
  "assets/icon-180.png": "cce27428858763d96b36898ac314ebe5da35c56c329cc0ab116228da3242cf1d",
  "assets/icon-192-v3.png": "a5d003fed9a72b6779baaae6d0d17f66ca511e60d33637d7a786269397a24916",
  "assets/icon-192.png": "a5d003fed9a72b6779baaae6d0d17f66ca511e60d33637d7a786269397a24916",
  "assets/icon-32-v3.png": "64ec0ac88d00effbb8576620b0d9be562971ab1f728d24a48b0c4b7248c9d061",
  "assets/icon-48-v3.png": "e39a2b45107ffe3867d35e4a416eb37d83f2fa5738ada126232bf4d8db4f2687",
  "assets/icon-512-v3.png": "2e752898669efed6e9f8469b3966440ef42880ca3225562f36f5219a5cc18473",
  "assets/icon-512.png": "2e752898669efed6e9f8469b3966440ef42880ca3225562f36f5219a5cc18473",
  "assets/icon-maskable-512-v3.png": "d00e643cd02df85653ebdd6fac6e241d47defea57c1c07e8ebad8c376f85e620",
  "assets/icon-maskable-512.png": "d00e643cd02df85653ebdd6fac6e241d47defea57c1c07e8ebad8c376f85e620",
  "assets/icon-v3.svg": "31a505732d687bb83e97140880b915547c6ca43dc619547bf094500de9807ad9",
  "assets/icon.svg": "31a505732d687bb83e97140880b915547c6ca43dc619547bf094500de9807ad9",
  "assets/lesson.js": "1128f26bb448e2c5cd1cd50076956ab569a680b582192e5babe0543960006841",
  "assets/model.js": "835f0aa26103e0251d5da2d00fed23c402be57d3ab45c8d7bac819c621fcc6c1",
  "assets/practice.js": "6ddbb3ba3fecf9490f4baa7845a572f510320f3170811527b5a3a1488484382f",
  "assets/style.css": "3018a1f6824f20d128aac20dc20e8f56eef5487afe433d173bfc5d633710e08e",
  "data/lessons.json": "00c11400aad8534be05fe3cf1fc8af09105f77073c544f09083b7ea09410b38c",
  "data/phrases.json": "86db192028c39d38ef029459971d5f402af72cdf93159ab90662114a046a812e",
  "field.html": "8239a4711a130e455c2f8638e4f78e9c51ccbfb035504dce44a7856fe0d1bf70",
  "index.html": "e13412dff5a6d832937daef53c8791aacffcb540a6cb93d90fe1e640165b64a8",
  "lessons/0001-arrival-greeting-car-exit.html": "3ebaf9611f1af3fc4028d72f0ffb4b6b017e3ce9939c68979cdbe5e1f83536b3",
  "lessons/0002-small-talk-dress-honeymoon.html": "87c2a35b1394f789e67a398798f20d7be0d453ce7a04bc7b40ef3e0405ba4132",
  "lessons/0003-breaking-the-ice-reassurance.html": "14d8f88fb7699b1c473d1c6300954e7908f2f11868427e2a851e52a3263eff4f",
  "lessons/0004-getting-to-know-the-couple.html": "d795ad85b1b6b973f2514ade341a0442eea3e722203ca0008bd2b29c49fa0d9b",
  "lessons/0005-week-1-review-roleplay.html": "140da23d8569aee78367fc9e0cff974beefdfaf98ff8dc087ce123157dca72d0",
  "lessons/0006-basic-pose-direction.html": "5c8ef9a3045165f408aab6356937bf8f15303f292d2e02aab895c983f0a8e982",
  "lessons/0007-directing-movement-sequences.html": "2da5669b81c5a65cc183600de722d0ee38627a01595209f78d316953b5284d60",
  "lessons/0008-directing-expressions-eye-contact.html": "7601cb5a22dcecd8703f6607dd8738ae58995f36e39e1e871a36dd9d760f44fb",
  "lessons/0009-micro-adjustment-direction.html": "b041c6bc49e7f21e8fb0ff42d66c678b1fb1e80e62a4cf26f4e238400de464fe",
  "lessons/0010-week-2-review-roleplay.html": "167368bded1ab344651a483df0769c87a7026264632646dc56d8b5fa1eae8129",
  "lessons/0011-specific-compliments.html": "c4e5e3cc2551a47fb91094d00bdb12d5629e9c532a26b0606003f3ba256ff942",
  "lessons/0012-handling-unexpected-situations.html": "358b749f933b687279a4cb0a31eac46499d01115ac1c14d111391ab11cea13a7",
  "lessons/0013-redirecting-heavy-conversations.html": "7062f0fd6cb2e87fc25a14be0dac2e57e9c843288f731f548c129e967d4f0d0d",
  "lessons/0014-recovery-strategies.html": "39211e8e75ec49d399ac353180ff9c1e1652d368c9f33d76462b75812ad5bfe8",
  "lessons/0015-week-3-review-roleplay.html": "51be8bf3628eca944e5ab6a9208027368c9e6edd6bf73e6b7421aa2e2cefa318",
  "lessons/0016-wrap-up-thank-you.html": "1021276cc9238ea660f52f8634713b2ccf183abc69fd49555d1b12ba5b1cbfab",
  "lessons/0017-following-up-on-deliverables.html": "7eb898e705c097613cc491c03415b9bb97252f0a56f96f2f41fcc76e94ab14cc",
  "lessons/0018-cross-cultural-client-communication.html": "fde635251da7817b145c6baefa1b2d39c149d763f41e929e02c4e28573bc6d61",
  "lessons/0019-comprehensive-freetalk.html": "696d4ab68b6bdd37218a822f3019a57b2da8090a79ac586383799cb45e695f4b",
  "lessons/0020-4-week-comprehensive-roleplay-self-asses.html": "2296a75dfe0b97a17796079bc9b34cec19bf2b8e91ff2f8bf9face3793706087",
  "manifest.webmanifest": "d1e92a693b238f60a4ddd36ee39c1ad54e4f7dbfceb288ac0e264b414a22172c",
  "practice.html": "f3e79dfe01d332943059cf95134e11f397c2a441b3d2ad2c2b215d5a5e81bc41",
  "./": "e13412dff5a6d832937daef53c8791aacffcb540a6cb93d90fe1e640165b64a8"
};
const PREFIX = 'kwe-' + encodeURIComponent(new URL(self.registration.scope).pathname) + '-';
const CACHE = PREFIX + VERSION;
const READY = new URL('__offline_ready__', self.registration.scope).href;
const urls = ASSETS.map(p => new URL(p, self.registration.scope).href);
async function verifiedFetch(url) {
  const response = await fetch(new Request(url, {cache:'reload'}));
  if (!response.ok) throw new Error('Release resource unavailable');
  const bytes = await crypto.subtle.digest('SHA-256', await response.clone().arrayBuffer());
  const hash = Array.from(new Uint8Array(bytes), b=>b.toString(16).padStart(2,'0')).join('');
  const index = urls.indexOf(url);
  if (hash !== HASHES[ASSETS[index]]) throw new Error('Release resource version mismatch');
  return response;
}
self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    try {
      await Promise.all(urls.map(async url => { const response = await verifiedFetch(url); await cache.put(url,response); }));
      await cache.put(READY, new Response(VERSION));
    } catch (error) {
      await caches.delete(CACHE);
      throw error;
    }
  })());
});
self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(key => key.startsWith(PREFIX) && key !== CACHE).map(key => caches.delete(key)));
    await self.clients.claim();
  })());
});
self.addEventListener('message', event => {
  if (event.data && event.data.type === 'ACTIVATE') { self.skipWaiting(); return; }
  if (event.data && event.data.type === 'STATUS' && event.ports[0]) {
    event.waitUntil((async () => {
      const cache = await caches.open(CACHE);
      const found = await Promise.all(urls.map(url => cache.match(url)));
      const ready = !!(await cache.match(READY)) && found.every(Boolean);
      event.ports[0].postMessage({ version: VERSION, ready, count: found.filter(Boolean).length });
    })());
  }
});
self.addEventListener('fetch', event => {
  const request = event.request, url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin || !url.href.startsWith(self.registration.scope)) return;
  url.search = ''; url.hash = '';
  if (urls.includes(url.href)) {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE), hit = await cache.match(url.href);
      if (hit) return hit;
      try { const response = await verifiedFetch(url.href); await cache.put(url.href,response.clone()); return response; }
      catch (error) { return new Response('저장된 버전의 파일을 불러오지 못했습니다. 온라인에서 업데이트를 확인해 주세요.', {status:503,headers:{'Content-Type':'text/plain;charset=utf-8'}}); }
    })()); return;
  }
  if (request.mode === 'navigate') event.respondWith(fetch(request).catch(() => new Response('<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>오프라인</title><body><h1>저장되지 않은 페이지입니다</h1><p>저장된 홈·현장·연습 화면을 사용해 주세요.</p><a href="' + self.registration.scope + 'index.html">홈 열기</a></body></html>', { status: 503, headers: { 'Content-Type': 'text/html;charset=utf-8' } })));
});
