/* Generated by tools/build-sw.cjs. Install atomically; upgrade on user action. */
const VERSION = 'v3-be700f5fe259';
const ASSETS = [
  "./",
  "assets/core.js",
  "assets/favicon-v3.ico",
  "assets/field.js",
  "assets/home.js",
  "assets/icon-1024-v3.png",
  "assets/icon-16-v3.png",
  "assets/icon-180-v3.png",
  "assets/icon-180.png",
  "assets/icon-192-v3.png",
  "assets/icon-192.png",
  "assets/icon-32-v3.png",
  "assets/icon-48-v3.png",
  "assets/icon-512-v3.png",
  "assets/icon-512.png",
  "assets/icon-maskable-512-v3.png",
  "assets/icon-maskable-512.png",
  "assets/icon-v3.svg",
  "assets/icon.svg",
  "assets/lesson.js",
  "assets/model.js",
  "assets/practice.js",
  "assets/style.css",
  "data/lessons.json",
  "data/phrases.json",
  "field.html",
  "index.html",
  "lessons/0001-arrival-greeting-car-exit.html",
  "lessons/0002-small-talk-dress-honeymoon.html",
  "lessons/0003-breaking-the-ice-reassurance.html",
  "lessons/0004-getting-to-know-the-couple.html",
  "lessons/0005-week-1-review-roleplay.html",
  "lessons/0006-basic-pose-direction.html",
  "lessons/0007-directing-movement-sequences.html",
  "lessons/0008-directing-expressions-eye-contact.html",
  "lessons/0009-micro-adjustment-direction.html",
  "lessons/0010-week-2-review-roleplay.html",
  "lessons/0011-specific-compliments.html",
  "lessons/0012-handling-unexpected-situations.html",
  "lessons/0013-redirecting-heavy-conversations.html",
  "lessons/0014-recovery-strategies.html",
  "lessons/0015-week-3-review-roleplay.html",
  "lessons/0016-wrap-up-thank-you.html",
  "lessons/0017-following-up-on-deliverables.html",
  "lessons/0018-cross-cultural-client-communication.html",
  "lessons/0019-comprehensive-freetalk.html",
  "lessons/0020-4-week-comprehensive-roleplay-self-asses.html",
  "manifest.webmanifest",
  "practice.html"
];
const HASHES = {
  "assets/core.js": "d054bcb5c7da6eafe24d483c42359d8b0f1826415cd74ff339cf9162d91bb367",
  "assets/favicon-v3.ico": "584b8eddfdb245bcb167c616ac54fddc95ebf6cdeeb501d28e984050dd36c8bb",
  "assets/field.js": "75a71826df3c2a6077a131141a982712d09c04454394acb8a713055c27e58efe",
  "assets/home.js": "cdb2ef53f070a0f7c08f6ea35f85d4f286f6a29a0162a5ba14125c7a47ad82e6",
  "assets/icon-1024-v3.png": "d0f2bb04eba45b5c86e1b36b7baa6206a7677245b9115eeb5cd060cc855f6f82",
  "assets/icon-16-v3.png": "f1e6c17d9c0c77d28053598b76e0aae169853184eb028d05935e8fdb8aee0637",
  "assets/icon-180-v3.png": "cce27428858763d96b36898ac314ebe5da35c56c329cc0ab116228da3242cf1d",
  "assets/icon-180.png": "cce27428858763d96b36898ac314ebe5da35c56c329cc0ab116228da3242cf1d",
  "assets/icon-192-v3.png": "a5d003fed9a72b6779baaae6d0d17f66ca511e60d33637d7a786269397a24916",
  "assets/icon-192.png": "a5d003fed9a72b6779baaae6d0d17f66ca511e60d33637d7a786269397a24916",
  "assets/icon-32-v3.png": "64ec0ac88d00effbb8576620b0d9be562971ab1f728d24a48b0c4b7248c9d061",
  "assets/icon-48-v3.png": "e39a2b45107ffe3867d35e4a416eb37d83f2fa5738ada126232bf4d8db4f2687",
  "assets/icon-512-v3.png": "2e752898669efed6e9f8469b3966440ef42880ca3225562f36f5219a5cc18473",
  "assets/icon-512.png": "2e752898669efed6e9f8469b3966440ef42880ca3225562f36f5219a5cc18473",
  "assets/icon-maskable-512-v3.png": "d00e643cd02df85653ebdd6fac6e241d47defea57c1c07e8ebad8c376f85e620",
  "assets/icon-maskable-512.png": "d00e643cd02df85653ebdd6fac6e241d47defea57c1c07e8ebad8c376f85e620",
  "assets/icon-v3.svg": "31a505732d687bb83e97140880b915547c6ca43dc619547bf094500de9807ad9",
  "assets/icon.svg": "31a505732d687bb83e97140880b915547c6ca43dc619547bf094500de9807ad9",
  "assets/lesson.js": "065379e144b91051fdf5676e74fe607af85901a7b3188f951f6382d1d2b1f2cd",
  "assets/model.js": "57911ce30777e52dd07e559f1bf5522f08425ec9fe9dbb5064bc874c41d7067a",
  "assets/practice.js": "6ddbb3ba3fecf9490f4baa7845a572f510320f3170811527b5a3a1488484382f",
  "assets/style.css": "e9401fa641420f8907531b49cd7216dffd7d73455ab746d591f566635ebdc897",
  "data/lessons.json": "00c11400aad8534be05fe3cf1fc8af09105f77073c544f09083b7ea09410b38c",
  "data/phrases.json": "86db192028c39d38ef029459971d5f402af72cdf93159ab90662114a046a812e",
  "field.html": "8239a4711a130e455c2f8638e4f78e9c51ccbfb035504dce44a7856fe0d1bf70",
  "index.html": "e13412dff5a6d832937daef53c8791aacffcb540a6cb93d90fe1e640165b64a8",
  "lessons/0001-arrival-greeting-car-exit.html": "63fd721fcf4802fcc068c901fb831a1aaf26c917dd03b65e3de29f231284604d",
  "lessons/0002-small-talk-dress-honeymoon.html": "13ea1a3b0348aa375cb5cf9e1fd5200da682ab85aea7abd3d6b4521011791b42",
  "lessons/0003-breaking-the-ice-reassurance.html": "cc1c0d4ad94c3d022ca403e710c81ffb17dcc1a3cf0ea41872e8090200444947",
  "lessons/0004-getting-to-know-the-couple.html": "1bce4b0ad29277a5db99d64a192ce4a667850cb86b27fe4c7bf0c4798d486b84",
  "lessons/0005-week-1-review-roleplay.html": "eed689fc98e21ecd9b8d0d0a8d44fa466315fd2a0d0d0ff08e5a4e94ba5374c6",
  "lessons/0006-basic-pose-direction.html": "417832323d744527ac5b5c1ef1cc5297648f87654b01bb4febf0f562b360de5e",
  "lessons/0007-directing-movement-sequences.html": "1d1a669600dc9e2f8618aeb2a4cc369c5a03bea53e267730acd8a17f5b402b81",
  "lessons/0008-directing-expressions-eye-contact.html": "9e4d22c8549f0168f959fb36f64a25229053949dc3f67c3058f49647c752a546",
  "lessons/0009-micro-adjustment-direction.html": "74048cfb458d9415cc82a54b74cb55376adfa670063570aef92af13590976968",
  "lessons/0010-week-2-review-roleplay.html": "d8b9ffaad62534f8170d76736230fa399cec12b7a7760431a55b24a77c7acecb",
  "lessons/0011-specific-compliments.html": "20a62e9cc3c2e3d03c342ba700400ddd6db75d02d65c557a59c25f014dc443d4",
  "lessons/0012-handling-unexpected-situations.html": "f29f81570b44c1dff3dd30c11d86c257a3394f099d48c114627cc25c477aa981",
  "lessons/0013-redirecting-heavy-conversations.html": "72f68f4cc73ad0623e818343ba57fe7a1b71c277b6065f96728ec871272cdbcf",
  "lessons/0014-recovery-strategies.html": "67d09473492085a27816fd8b6634c45087368227c5d4f900e4328e443c8999c0",
  "lessons/0015-week-3-review-roleplay.html": "c93b6523a93f44bb269511d46352ba2092544c1d0154e259e6ad392b4aaf2144",
  "lessons/0016-wrap-up-thank-you.html": "f3d0b225f8514c53324981bbd94e85575c7a5bf682cb3e64dfd30d881ca0714a",
  "lessons/0017-following-up-on-deliverables.html": "fa2f66eef25c6b638656e2c492f816ab84b860e0b1182d3e4bd7fda905af4f6d",
  "lessons/0018-cross-cultural-client-communication.html": "d1aa02ab4f4e52f3bf209659bfafe8e1466347ec594ed4915668c2fcdec55b90",
  "lessons/0019-comprehensive-freetalk.html": "ba6534f2d8e83c4f29f53c83cc900e61413af5501f9af81ba0357ea75ed685be",
  "lessons/0020-4-week-comprehensive-roleplay-self-asses.html": "e805c1f369c2c3eece7e20d06d384bd337832842ced261d70c6c777fa0a6683d",
  "manifest.webmanifest": "d1e92a693b238f60a4ddd36ee39c1ad54e4f7dbfceb288ac0e264b414a22172c",
  "practice.html": "f3e79dfe01d332943059cf95134e11f397c2a441b3d2ad2c2b215d5a5e81bc41",
  "./": "e13412dff5a6d832937daef53c8791aacffcb540a6cb93d90fe1e640165b64a8"
};
const PREFIX = 'kwe-' + encodeURIComponent(new URL(self.registration.scope).pathname) + '-';
const CACHE = PREFIX + VERSION;
const READY = new URL('__offline_ready__', self.registration.scope).href;
const urls = ASSETS.map(p => new URL(p, self.registration.scope).href);
async function verifiedFetch(url) {
  const response = await fetch(new Request(url, {cache:'reload'}));
  if (!response.ok) throw new Error('Release resource unavailable');
  const bytes = await crypto.subtle.digest('SHA-256', await response.clone().arrayBuffer());
  const hash = Array.from(new Uint8Array(bytes), b=>b.toString(16).padStart(2,'0')).join('');
  const index = urls.indexOf(url);
  if (hash !== HASHES[ASSETS[index]]) throw new Error('Release resource version mismatch');
  return response;
}
self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    try {
      await Promise.all(urls.map(async url => { const response = await verifiedFetch(url); await cache.put(url,response); }));
      await cache.put(READY, new Response(VERSION));
    } catch (error) {
      await caches.delete(CACHE);
      throw error;
    }
  })());
});
self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter(key => key.startsWith(PREFIX) && key !== CACHE).map(key => caches.delete(key)));
    await self.clients.claim();
  })());
});
self.addEventListener('message', event => {
  if (event.data && event.data.type === 'ACTIVATE') { self.skipWaiting(); return; }
  if (event.data && event.data.type === 'STATUS' && event.ports[0]) {
    event.waitUntil((async () => {
      const cache = await caches.open(CACHE);
      const found = await Promise.all(urls.map(url => cache.match(url)));
      const ready = !!(await cache.match(READY)) && found.every(Boolean);
      event.ports[0].postMessage({ version: VERSION, ready, count: found.filter(Boolean).length });
    })());
  }
});
self.addEventListener('fetch', event => {
  const request = event.request, url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin || !url.href.startsWith(self.registration.scope)) return;
  url.search = ''; url.hash = '';
  if (urls.includes(url.href)) {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE), hit = await cache.match(url.href);
      if (hit) return hit;
      try { const response = await verifiedFetch(url.href); await cache.put(url.href,response.clone()); return response; }
      catch (error) { return new Response('저장된 버전의 파일을 불러오지 못했습니다. 온라인에서 업데이트를 확인해 주세요.', {status:503,headers:{'Content-Type':'text/plain;charset=utf-8'}}); }
    })()); return;
  }
  if (request.mode === 'navigate') event.respondWith(fetch(request).catch(() => new Response('<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>오프라인</title><body><h1>저장되지 않은 페이지입니다</h1><p>저장된 홈·현장·연습 화면을 사용해 주세요.</p><a href="' + self.registration.scope + 'index.html">홈 열기</a></body></html>', { status: 503, headers: { 'Content-Type': 'text/html;charset=utf-8' } })));
});
