const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const M = require('../assets/model.js');
const root = path.resolve(__dirname,'..');
const phrases = JSON.parse(fs.readFileSync(path.join(root,'data/phrases.json'))).phrases;
const id = 'tilt-your-chin-down-just-a-little';
function oldState() { return {version:2,lessons:{'1':{done:true,first:'2026-09-01',last:'2026-09-02',due:'2026-09-05',reps:2,ease:2.5,interval:3,lapses:0}},cards:{[id]:{reps:1,ease:2.3,interval:1,due:'2026-09-05',last:'2026-09-04'}},pins:[id],days:{'2026-09-02':{lessons:[1],cards:1,quiz:[1,2]}},checks:{'1':[true,false]},settings:{theme:'dark',size:20,voice:'Samantha',rate:.85,outdoor:false,showKo:false}}; }
function browserCore(raw, legacy) {
 const storage = new Map(); if(raw!==undefined)storage.set('kwe_state_v2',JSON.stringify(raw));if(legacy)storage.set('kwe_progress_v1',JSON.stringify(legacy));
 const context = {KWEModel:M,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},setTimeout:()=>0,clearTimeout(){},console,document:{documentElement:{setAttribute(){},removeAttribute(){}},body:{classList:{toggle(){}},style:{setProperty(){}},appendChild(){}},getElementById:()=>null,createElement:()=>({setAttribute(){},classList:{add(){},remove(){}},textContent:''})},navigator:{},Date,URL};context.window=context;
 vm.runInNewContext(fs.readFileSync(path.join(root,'assets/core.js'),'utf8'),context);
 return {api:context.KWE,storage};
}
test('v2 migration keeps IDs, schedules, settings and checks intact',()=>{const raw=oldState(),n=M.normalize(raw);assert.equal(n.version,3);for(const k of ['lessons','cards','pins','days','checks'])assert.deepEqual(n[k],raw[k]);for(const k of Object.keys(raw.settings))assert.equal(n.settings[k],raw.settings[k]);assert.deepEqual(n.kit,[]);});
for(const [query,wanted] of [['턱 내려',id],['턱내려',id],['좀 가까이','come-a-little-closer-to-each-other'],['웃지 말고','you-can-stop-smiling-like-it-s-a-passport-photo'],['단체사진','everyone-squeeze-in-closer-than-feels-normal'],['CHIN DOWN',id],['비 와','it-looks-like-it-might-rain-let-s-move-to-plan-b'],['못 알아들었어','sorry-could-you-say-that-one-more-time']])test('useful first result: '+query,()=>assert.equal(M.search(phrases,query,'all')[0].id,wanted));
test('category filtering and empty results are explicit',()=>{assert.equal(M.search(phrases,'턱 내려','arrival').length,0);assert.equal(M.search(phrases,'없는말xyz','all').length,0);});
test('pending review precedes unseen expressions; short sets are bounded',()=>{const s=M.normalize(oldState());assert.equal(M.deck(phrases,s,'quick','2026-10-02')[0],id);assert.equal(M.deck(phrases,s,'quick','2026-10-02').length,5);assert.equal(M.deck(phrases,s,'flash','2026-10-02').length,10);assert.deepEqual(M.deck(phrases,s,'saved','2026-10-02'),[id]);});
test('hard and shooting kit sources obey actual user choices',()=>{const s=M.normalize(oldState());s.cards[id].lastGrade=3;s.kit=[phrases[1].id,id];assert.deepEqual(M.deck(phrases,s,'hard','2026-10-02'),[id]);assert.deepEqual(M.deck(phrases,s,'kit','2026-10-02'),s.kit);});
test('invalid and future backups fail before replacing state',()=>{for(const change of [{version:99},{pins:'bad'},{settings:{rate:Infinity}},{cards:{a:{due:'2026-02-30'}}},{cards:{a:{reps:5}}},{days:{'2026-10-02':{lessons:[],cards:1,quiz:[5,2]}}},{session:{mode:'quick',date:'2026-10-02',ids:[id],index:3,revealed:false,right:0}}])assert.throws(()=>M.normalize({...oldState(),...change}));assert.throws(()=>M.normalize(JSON.parse('{"lessons":{},"__proto__":{}}')));});
test('outdoor mode restores prior theme and font size',()=>{const {api}=browserCore(oldState());api.load();api.toggleOutdoor();assert.equal(api.get('theme'),'light');assert.equal(api.get('size'),22);api.toggleOutdoor();assert.equal(api.get('theme'),'dark');assert.equal(api.get('size'),20);});
test('future local data is never overwritten by a save action',()=>{const raw={...oldState(),version:9},{api,storage}=browserCore(raw);api.load();assert.equal(api.save(),false);assert.deepEqual(JSON.parse(storage.get('kwe_state_v2')),raw);});
test('legacy v1 progress remains available after upgrade',()=>{const {api}=browserCore(undefined,{'1':{completed:true,date:'2026-09-10'}});assert.equal(api.load().lessons['1'].done,true);assert.equal(api.load().lessons['1'].first,'2026-09-10');assert.equal(api.load().version,3);});
test('all original expression IDs and all lesson URLs survive',()=>{const original=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/original-ids.json')));for(const id of original)assert.ok(phrases.some(p=>p.id===id));const lessons=JSON.parse(fs.readFileSync(path.join(root,'data/lessons.json')));assert.deepEqual(lessons.filter(l=>!l.extra).map(l=>l.id),Array.from({length:20},(_,i)=>i+1));for(const l of lessons)assert.ok(fs.existsSync(path.join(root,'lessons',l.filename)));});
test('generated service worker contains hashes for every release asset',()=>{const source=fs.readFileSync(path.join(root,'sw.js'),'utf8');const assets=JSON.parse(source.match(/const ASSETS = (\[[\s\S]*?\]);/)[1]);const hashes=JSON.parse(source.match(/const HASHES = ({[\s\S]*?});/)[1]);for(const f of assets){assert.match(hashes[f],/^[a-f0-9]{64}$/);if(f!=='./')assert.ok(fs.existsSync(path.join(root,f)));}assert.ok(source.includes("key.startsWith(PREFIX)"));assert.ok(!source.includes('.catch(() => self.skipWaiting())'));});

test('large saved collections rotate to expressions not yet rehearsed',()=>{const s=M.normalize(oldState());s.pins=phrases.slice(0,24).map(p=>p.id);s.kit=s.pins.slice();for(const mode of ['saved','kit']){const first=M.deck(phrases,s,mode,'2026-10-02');for(const id of first)s.cards[id]={reps:1,ease:2.5,interval:1,due:'2026-10-03',last:'2026-10-02'};const next=M.deck(phrases,s,mode,'2026-10-02');assert.equal(next.length,10);assert.ok(next.some(id=>!first.includes(id)));}});

const sentenceId='lesson-sentence-'+'a'.repeat(24);
const savedSentence={id:sentenceId,en:'No rush at all.',ko:'서두르지 않으셔도 돼요.',cat:'arrival',situation:'도착 인사 · 상황 예시',note:'Lesson 1 · 상황 예시.',lessons:[1],src:'saved-lesson'};
test('old v3 backups remain valid without supplemental lesson sentences',()=>{const raw={...oldState(),version:3};const state=M.normalize(raw);assert.deepEqual(state.sentences,{});assert.deepEqual(state.pins,raw.pins);});
test('saved lesson sentences survive backup validation and malformed records fail',()=>{const raw={...oldState(),sentences:{[sentenceId]:savedSentence},pins:[id,sentenceId]};assert.deepEqual(M.normalize(JSON.parse(JSON.stringify(raw))).sentences[ sentenceId ],savedSentence);for(const change of [{id:'wrong'},{en:''},{cat:'bad/category'},{lessons:[0]},{lessons:[1.5]},{lessons:[1001]},{src:'wrong'},{note:7},{html:'<script>'}])assert.throws(()=>M.normalize({...raw,sentences:{[sentenceId]:{...savedSentence,...change}}}));});
test('lesson save shares canonical pins and rolls back a blocked supplemental save',()=>{const {api}=browserCore(oldState());assert.equal(api.toggleSentence({id,en:'Chin down.'}),false);assert.equal(api.toggleSentence({id,en:'Chin down.'}),true);assert.equal(api.load().pins.filter(x=>x===id).length,1);assert.equal(api.toggleSentence(savedSentence),true);assert.equal(api.load().sentences[sentenceId].en,savedSentence.en);const future=browserCore({...oldState(),version:99});assert.equal(future.api.toggleSentence(savedSentence),null);assert.equal(future.api.load().sentences[sentenceId],undefined);});
test('all generated lesson save controls resolve to canonical IDs or validated sentence snapshots',()=>{const lessons=JSON.parse(fs.readFileSync(path.join(root,'data/lessons.json')));const canonical=new Set(phrases.map(p=>p.id));for(const lesson of lessons){const html=fs.readFileSync(path.join(root,'lessons',lesson.filename),'utf8');const library=JSON.parse(html.match(/<script type="application\/json" id="lesson-sentences">([\s\S]*?)<\/script>/)[1]);for(const [,savedId] of html.matchAll(/data-sentence-save="([^"]+)"/g)){const p=library[savedId];assert.ok(p,`${lesson.id}: ${savedId}`);if(!canonical.has(savedId))assert.doesNotThrow(()=>M.normalize({lessons:{},sentences:{[savedId]:p}}));}for(const expression of lesson.expressions){const p=phrases.find(p=>p.en===expression.en);assert.ok(html.includes(`data-sentence-save="${p.id}"`));}}});

test('supplemental group lesson teaches all six existing expressions without changing IDs',()=>{const lessons=JSON.parse(fs.readFileSync(path.join(root,'data/lessons.json')));const group=lessons.find(l=>l.id===21);assert.ok(group.extra);assert.equal(group.expressions.length,6);const canonical=phrases.filter(p=>p.cat==='group'&&p.lessons.includes(21));assert.equal(canonical.length,6);for(const p of canonical){assert.ok(group.expressions.some(x=>x.en===p.en&&x.ko===p.ko));assert.ok(p.lessons.includes(21));}assert.ok(group.scenarios.length>=3&&group.quiz.length>=3);});
test('supplemental lesson sentences and completed progress survive backup restoration',()=>{const original=oldState(),extra={...savedSentence,lessons:[21],cat:'group'};const raw={...original,version:3,sentences:{[sentenceId]:extra},lessons:{...original.lessons,'21':{done:true,first:'2026-10-04',last:'2026-10-04',due:'2026-10-05',reps:1,ease:2.5,interval:1,lapses:0}},lastLesson:'21',checks:{...original.checks,'21':[true,false]},quizAnswers:{'21':[0,1,1]},days:{...original.days,'2026-10-04':{lessons:[21],cards:0,quiz:[0,0]}}};const restored=M.normalize(JSON.parse(JSON.stringify(raw)));for(const key of ['lessons','sentences','checks','quizAnswers','days','lastLesson'])assert.deepEqual(restored[key],raw[key]);assert.deepEqual(restored.pins,original.pins);assert.deepEqual(restored.cards,original.cards);});

test('friends photo search separates jokes, action prompts and a quiet fallback',()=>{
 assert.equal(M.search(phrases,'친구사진','group').length,8);
 for(const [query,wanted] of [
  ['그룹 농담','friends-relax-this-isn-t-a-passport-photo'],
  ['진지한 척','friends-one-serious-photo-try-not-to-laugh'],
  ['환호','friends-on-three-cheer-for-these-two'],
  ['앨범 커버','friends-give-me-your-best-album-cover-pose'],
  ['농담 반응 없음','friends-no-pose-needed-just-enjoy-being-together']
 ])assert.equal(M.search(phrases,query,'group')[0].id,wanted,query);
});
